CREATE TABLE Customer (
	cid 		BIGINT 			PRIMARY KEY	AUTO_INCREMENT,
    name 		VARCHAR(30)		NOT NULL,
    ssn 		CHAR(14)		NOT NULL,
    regDate 	TIMESTAMP		NOT NULL	DEFAULT CURRENT_TIMESTAMP
)AUTO_INCREMENT = 1001;


CREATE TABLE Account(
	aid 			BIGINT		PRIMARY KEY		AUTO_INCREMENT,
	accType			CHAR(1)		NOT NULL	DEFAULT 'S',
	balance			DOUBLE		NOT NULL 	DEFAULT 0.0,
	interestRate 	DOUBLE		NOT NULL 	DEFAULT 0.0,
	overdraftAmount	DOUBLE		NOT NULL	DEFAULT 0.0,
	customerId		BIGINT		NOT NULL,
	regDATE			TIMESTAMP	NOT NULL	DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT Account_CustomerId_FK	FOREIGN KEY (customerId) REFERENCES Customer(cid)
)AUTO_INCREMENT = 2002;